database:
  log_queries: true
  psn: "postgres://armando:dev@localhost:5432/movie"

server:
  port: :8081
  debug: true
  read_timeout_seconds: 15
  write_timeout_seconds: 20

jwt:
  secret: testing # Change this value
  duration_minutes: 1000
  refresh_duration_minutes: 10
  max_refresh_minutes: 144
  signing_algorithm: HS384

application:
  min_password_strength: 3
  swagger_ui_path: assets/swagger